version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5099:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 1s
      retries: 3

  backend:
    build: .
    command: sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NANE=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: