version: '3.9'

services:
  backend:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NANE=postgres_db_name
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_NAME=postgres_db_name
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_USER=db
